# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: java cicd flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/money-manager-container:latest .

      - name: Push Docker Hub
        run: docker push ${{secrets.DOCKER_USERNAME}}/money-manager-container:latest

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop be-web
            docker rm be-web
            docker rmi nhatkhuong/money-manager-container:latest
            docker pull nhatkhuong/money-manager-container:latest
            docker run -d -p 8080:8080 --name be-web nhatkhuong/money-manager-container:latest
 

